name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "b61790e2418ecb8ed2c1a4efe694d7683abc2ff9"
          ado_organization: "RealCoreSupport"
          ado_project: "Support"
          ado_wit: "Impediment"
          ado_new_state: "New"
          ado_close_state: "Closed"
          ado_bypassrules: true
