name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "auz7grbxwoufmdqzpvsgsauyaq6spiridqkzdudcp4enpmkq3dbq"
          github_token: "7upl2qsco2ynays4rilio2ycuf2f644kija2orqv2udrebxkzxba"
          ado_organization: "ado_organization_name"
          ado_project: "Support"
          ado_area_path: "Support"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_close_state: "Closed"
          ado_bypassrules: true
